Feature/postlist
kyutech-programming-club/proken pull request #7
Opened 2020-09-27 07:29 UTC by o-xian999

やったこと
- 複数のMarkdownファイルから投稿一覧を作成。
- MarkdownのCSS(HTMLでいう`h1`や`h3`)が聞かなかったので、`config`のTailwindCSSとPurgeCSSの記述を一旦コメントアウトしました。

2020-09-27 07:38 UTC, syu-kwsk commented on posts/1.md
> +ほげほげあひあひ
まぁいいけど……。

2020-09-27 07:39 UTC, syu-kwsk commented on src/templates/Post.vue
> +  </article>
[question]  
<article></article>ってどういうときに使うの？

2020-09-27 07:47 UTC, syu-kwsk commented
@o-xian999  さん  
posts配下の記事だけあるように見えるのですが、実際はさらにその下でproduct/とかevents/とかに分かれるのではなかったですか？記事を複数のディレクトリに分けても表示できる必要があると思います。

2020-09-28 11:55 UTC, syu-kwsk commented on gridsome.config.js
> +    // },
あとあとめんどくなりそうなので、消しとく…？

2020-09-28 12:00 UTC, syu-kwsk requested changes

2020-09-28 12:00 UTC, syu-kwsk commented on gridsome.config.js
> +    // },
@o-xian999 さん  
後々めんどくなりそうなので、消しとこ。
tailwindの方は未定ってことで

2020-09-28 12:25 UTC, o-xian999 commented on gridsome.config.js
> +    // },
分かりました。消しておきますね。

2020-09-28 14:03 UTC, syu-kwsk approved these changes
LGTM

2020-09-28 14:04 UTC, o-xian999 commented
PostListをトップページに表示

2020-09-28 14:04 UTC, merged